# Generated by Django 5.0.6 on 2024-10-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("uid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("upImageCaption", models.TextField()),
                ("downImageCaption", models.TextField()),
                ("image", models.ImageField(upload_to="Post-Images")),
                ("dateCreated", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
