# Generated by Django 5.0.6 on 2024-10-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date",
            field=models.BooleanField(default=True),
        ),
    ]
