# Generated by Django 5.0.6 on 2024-10-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0002_post_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, upload_to="Post-Images"),
        ),
        migrations.AlterField(
            model_name="post",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
